def seed_countries

  Country.destroy_all

  countries_attributes = [
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Afghanistan.png"), phone_code: "+93", name: "Afghanistan", alpha2_code: " AF", alpha3_code: "AFG", numeric_code: "004"},
      {   flag: nil, phone_code: "+", name: "Aland Islands", alpha2_code: "AX", alpha3_code: "ALA", numeric_code: "248"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Albania.png"), phone_code: "+355", name: "Albania", alpha2_code: "AL", alpha3_code: "ALB", numeric_code: "008"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Algeria.png"), phone_code: "+213", name: "Algeria", alpha2_code: "DZ", alpha3_code: "DZA", numeric_code: "012"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of American Samoa.png"), phone_code: "+", name: "American Samoa", alpha2_code: "AS", alpha3_code: "ASM", numeric_code: "016"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Andorra.png"), phone_code: "+376", name: "Andorra", alpha2_code: "AD", alpha3_code: "AND", numeric_code: "020"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Angola.png"), phone_code: "+244", name: "Angola", alpha2_code: "AO", alpha3_code: "AGO", numeric_code: "024"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Anguilla.png"), phone_code: "+264", name: "Anguilla", alpha2_code: "AI", alpha3_code: "AIA", numeric_code: "660"},
      {   flag: nil, phone_code: "+", name: "Antarctica", alpha2_code: "AQ", alpha3_code: "ATA", numeric_code: "010"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Antigua and Barbuda.png"), phone_code: "+268", name: "Antigua and Barbuda", alpha2_code: "AG", alpha3_code: "ATG", numeric_code: "028"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Argentina.png"), phone_code: "+54", name: "Argentina", alpha2_code: "AR", alpha3_code: "ARG", numeric_code: "032"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Armenia.png"), phone_code: "+374", name: "Armenia", alpha2_code: "AM", alpha3_code: "ARM", numeric_code: "051"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Aruba.png"), phone_code: "+297", name: "Aruba", alpha2_code: "AW", alpha3_code: "ABW", numeric_code: "533"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Australia.png"), phone_code: "+61", name: "Australia", alpha2_code: "AU", alpha3_code: "AUS", numeric_code: "036"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Austria.png"), phone_code: "+43", name: "Austria", alpha2_code: "AT", alpha3_code: "AUT", numeric_code: "040"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Azerbaijan.png"), phone_code: "+994", name: "Azerbaijan", alpha2_code: "AZ", alpha3_code: "AZE", numeric_code: "031"},
      {   flag: nil, phone_code: "+242", name: "Bahamas", alpha2_code: "BS", alpha3_code: "BHS", numeric_code: "044"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bahrain.png"), phone_code: "+973", name: "Bahrain", alpha2_code: "BH", alpha3_code: "BHR", numeric_code: "048"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bangladesh.png"), phone_code: "+880", name: "Bangladesh", alpha2_code: "BD", alpha3_code: "BGD", numeric_code: "050"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Barbados.png"), phone_code: "+246", name: "Barbados", alpha2_code: "BB", alpha3_code: "BRB", numeric_code: "052"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Belarus.png"), phone_code: "+375", name: "Belarus", alpha2_code: "BY", alpha3_code: "BLR", numeric_code: "112"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Belgium.png"), phone_code: "+32", name: "Belgium", alpha2_code: "BE", alpha3_code: "BEL", numeric_code: "056"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Belize.png"), phone_code: "+501", name: "Belize", alpha2_code: "BZ", alpha3_code: "BLZ", numeric_code: "084"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Benin.png"), phone_code: "+229", name: "Benin", alpha2_code: "BJ", alpha3_code: "BEN", numeric_code: "204"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bermuda.png"), phone_code: "+441", name: "Bermuda", alpha2_code: "BM", alpha3_code: "BMU", numeric_code: "060"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bhutan.png"), phone_code: "+975", name: "Bhutan", alpha2_code: "BT", alpha3_code: "BTN", numeric_code: "064"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bolivia.png"), phone_code: "+591", name: "Bolivia", alpha2_code: "BO", alpha3_code: "BOL", numeric_code: "068"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bosnia and Herzegovina.png"), phone_code: "+387", name: "Bosnia and Herzegovina", alpha2_code: "BA", alpha3_code: "BIH", numeric_code: "070"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Botswana.png"), phone_code: "+267", name: "Botswana", alpha2_code: "BW", alpha3_code: "BWA", numeric_code: "072"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bouvet Island.png"), phone_code: "+", name: "Bouvet Island", alpha2_code: "BV", alpha3_code: "BVT", numeric_code: "074"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Brazil.png"), phone_code: "+55", name: "Brazil", alpha2_code: "BR", alpha3_code: "BRA", numeric_code: "076"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of British Virgin Islands.png"), phone_code: "+284", name: "British Virgin Islands", alpha2_code: "VG", alpha3_code: "VGB", numeric_code: "092"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of British Indian Ocean Territory.png"), phone_code: "+", name: "British Indian Ocean Territory", alpha2_code: "IO", alpha3_code: "IOT", numeric_code: "086"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Brunei.png"), phone_code: "+673", name: "Brunei Darussalam", alpha2_code: "BN", alpha3_code: "BRN", numeric_code: "096"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Bulgaria.png"), phone_code: "+359", name: "Bulgaria", alpha2_code: "BG", alpha3_code: "BGR", numeric_code: "100"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Burkina Faso.png"), phone_code: "+226", name: "Burkina Faso", alpha2_code: "BF", alpha3_code: "BFA", numeric_code: "854"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Burundi.png"), phone_code: "+257", name: "Burundi", alpha2_code: "BI", alpha3_code: "BDI", numeric_code: "108"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cambodia.png"), phone_code: "+855", name: "Cambodia", alpha2_code: "KH", alpha3_code: "KHM", numeric_code: "116"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cameroon.png"), phone_code: "+237", name: "Cameroon", alpha2_code: "CM", alpha3_code: "CMR", numeric_code: "120"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Canada.png"), phone_code: "+2", name: "Canada", alpha2_code: "CA", alpha3_code: "CAN", numeric_code: "124"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cape Verde.png"), phone_code: "+238", name: "Cape Verde", alpha2_code: "CV", alpha3_code: "CPV", numeric_code: "132"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cayman Islands.png"), phone_code: "+345", name: "Cayman Islands", alpha2_code: "KY", alpha3_code: "CYM", numeric_code: "136"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Central African Republic.png"), phone_code: "+236", name: "Central African Republic", alpha2_code: "CF", alpha3_code: "CAF", numeric_code: "140"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Chad.png"), phone_code: "+235", name: "Chad", alpha2_code: "TD", alpha3_code: "TCD", numeric_code: "148"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Chile.png"), phone_code: "+56", name: "Chile", alpha2_code: "CL", alpha3_code: "CHL", numeric_code: "152"},
      {   flag: nil, phone_code: "+86", name: "Hong Kong, SAR China", alpha2_code: "HK", alpha3_code: "HKG", numeric_code: "344"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Macau.png"), phone_code: "+86", name: "Macao, SAR China", alpha2_code: "MO", alpha3_code: "MAC", numeric_code: "446"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Christmas Islands.png"), phone_code: "+", name: "Christmas Island", alpha2_code: "CX", alpha3_code: "CXR", numeric_code: "162"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cocos (Keeling) Islands.png"), phone_code: "+", name: "Cocos (Keeling) Islands", alpha2_code: "CC", alpha3_code: "CCK", numeric_code: "166"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Colombia.png"), phone_code: "+57", name: "Colombia", alpha2_code: "CO", alpha3_code: "COL", numeric_code: "170"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Comoros.png"), phone_code: "+269", name: "Comoros", alpha2_code: "KM", alpha3_code: "COM", numeric_code: "174"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Republic of the Congo.png"), phone_code: "+242", name: "Congo (Brazzaville)", alpha2_code: "CG", alpha3_code: "COG", numeric_code: "178"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Democratic Republic of the Congo.png"), phone_code: "+242", name: "Congo (Kinshasa)", alpha2_code: "CD", alpha3_code: "COD", numeric_code: "180"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cook Islands.png"), phone_code: "+682", name: "Cook Islands ", alpha2_code: "CK", alpha3_code: "COK", numeric_code: "184"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Costa Rica.png"), phone_code: "+506", name: "Costa Rica", alpha2_code: "CR", alpha3_code: "CRI", numeric_code: "188"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cote divoire.png"), phone_code: "+", name: "C&ocirc;te d'Ivoire", alpha2_code: "CI", alpha3_code: "CIV", numeric_code: "384"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Croatia.png"), phone_code: "+385", name: "Croatia", alpha2_code: "HR", alpha3_code: "HRV", numeric_code: "191"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cuba.png"), phone_code: "+53", name: "Cuba", alpha2_code: "CU", alpha3_code: "CUB", numeric_code: "192"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Cyprus.png"), phone_code: "+357", name: "Cyprus", alpha2_code: "CY", alpha3_code: "CYP", numeric_code: "196"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Czech Republic.png"), phone_code: "+420", name: "Czech Republic", alpha2_code: "CZ", alpha3_code: "CZE", numeric_code: "203"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Denmark.png"), phone_code: "+45", name: "Denmark", alpha2_code: "DK", alpha3_code: "DNK", numeric_code: "208"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Djibouti.png"), phone_code: "+253", name: "Djibouti", alpha2_code: "DJ", alpha3_code: "DJI", numeric_code: "262"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Dominica.png"), phone_code: "+767", name: "Dominica", alpha2_code: "DM", alpha3_code: "DMA", numeric_code: "212"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Dominican Republic.png"), phone_code: "+809", name: "Dominican Republic", alpha2_code: "DO", alpha3_code: "DOM", numeric_code: "214"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Ecuador.png"), phone_code: "+593", name: "Ecuador", alpha2_code: "EC", alpha3_code: "ECU", numeric_code: "218"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Egypt.png"), phone_code: "+20", name: "Egypt", alpha2_code: "EG", alpha3_code: "EGY", numeric_code: "818"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of El Salvador.png"), phone_code: "+503", name: "El Salvador", alpha2_code: "SV", alpha3_code: "SLV", numeric_code: "222"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Equatorial Guinea.png"), phone_code: "+240", name: "Equatorial Guinea", alpha2_code: "GQ", alpha3_code: "GNQ", numeric_code: "226"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Eritrea.png"), phone_code: "+291", name: "Eritrea", alpha2_code: "ER", alpha3_code: "ERI", numeric_code: "232"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Estonia.png"), phone_code: "+372", name: "Estonia", alpha2_code: "EE", alpha3_code: "EST", numeric_code: "233"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Ethiopia.png"), phone_code: "+251", name: "Ethiopia", alpha2_code: "ET", alpha3_code: "ETH", numeric_code: "231"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Falkland Islands (Islas Malvinas).png"), phone_code: "+500", name: "Falkland Islands (Malvinas) ", alpha2_code: "FK", alpha3_code: "FLK", numeric_code: "238"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Faroe Islands.png"), phone_code: "+298", name: "Faroe Islands", alpha2_code: "FO", alpha3_code: "FRO", numeric_code: "234"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Fiji.png"), phone_code: "+679", name: "Fiji", alpha2_code: "FJ", alpha3_code: "FJI", numeric_code: "242"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Finland.png"), phone_code: "+358", name: "Finland", alpha2_code: "FI", alpha3_code: "FIN", numeric_code: "246"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of France.png"), phone_code: "+33", name: "France", alpha2_code: "FR", alpha3_code: "FRA", numeric_code: "250"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guyana.png"), phone_code: "+594", name: "French Guiana", alpha2_code: "GF", alpha3_code: "GUF", numeric_code: "254"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of French Polynesia.png"), phone_code: "+689", name: "French Polynesia", alpha2_code: "PF", alpha3_code: "PYF", numeric_code: "258"},
      {   flag: nil, phone_code: "+", name: "French Southern Territories", alpha2_code: "TF", alpha3_code: "ATF", numeric_code: "260"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Gabon.png"), phone_code: "+241", name: "Gabon", alpha2_code: "GA", alpha3_code: "GAB", numeric_code: "266"},
      {   flag: nil, phone_code: "+220", name: "Gambia", alpha2_code: "GM", alpha3_code: "GMB", numeric_code: "270"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Georgia.png"), phone_code: "+995", name: "Georgia", alpha2_code: "GE", alpha3_code: "GEO", numeric_code: "268"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Germany.png"), phone_code: "+49", name: "Germany", alpha2_code: "DE", alpha3_code: "DEU", numeric_code: "276"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Ghana.png"), phone_code: "+233", name: "Ghana", alpha2_code: "GH", alpha3_code: "GHA", numeric_code: "288"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Gibraltar.png"), phone_code: "+350", name: "Gibraltar ", alpha2_code: "GI", alpha3_code: "GIB", numeric_code: "292"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Greece.png"), phone_code: "+30", name: "Greece", alpha2_code: "GR", alpha3_code: "GRC", numeric_code: "300"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Greenland.png"), phone_code: "+299", name: "Greenland", alpha2_code: "GL", alpha3_code: "GRL", numeric_code: "304"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Grenada.png"), phone_code: "+473", name: "Grenada", alpha2_code: "GD", alpha3_code: "GRD", numeric_code: "308"},
      {   flag: nil, phone_code: "+590", name: "Guadeloupe", alpha2_code: "GP", alpha3_code: "GLP", numeric_code: "312"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guam.png"), phone_code: "+", name: "Guam", alpha2_code: "GU", alpha3_code: "GUM", numeric_code: "316"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guatemala.png"), phone_code: "+502", name: "Guatemala", alpha2_code: "GT", alpha3_code: "GTM", numeric_code: "320"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guernsey.png"), phone_code: "+", name: "Guernsey", alpha2_code: "GG", alpha3_code: "GGY", numeric_code: "831"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guinea.png"), phone_code: "+224", name: "Guinea", alpha2_code: "GN", alpha3_code: "GIN", numeric_code: "324"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guinea Bissau.png"), phone_code: "+245", name: "Guinea-Bissau", alpha2_code: "GW", alpha3_code: "GNB", numeric_code: "624"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Guyana.png"), phone_code: "+592", name: "Guyana", alpha2_code: "GY", alpha3_code: "GUY", numeric_code: "328"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Haiti.png"), phone_code: "+509", name: "Haiti", alpha2_code: "HT", alpha3_code: "HTI", numeric_code: "332"},
      {   flag: nil, phone_code: "+", name: "Heard and Mcdonald Islands", alpha2_code: "HM", alpha3_code: "HMD", numeric_code: "334"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Holy See (Vatican City).png"), phone_code: "+", name: "Holy See (Vatican City State)", alpha2_code: "VA", alpha3_code: "VAT", numeric_code: "336"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Honduras.png"), phone_code: "+504", name: "Honduras", alpha2_code: "HN", alpha3_code: "HND", numeric_code: "340"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Hungary.png"), phone_code: "+36", name: "Hungary", alpha2_code: "HU", alpha3_code: "HUN", numeric_code: "348"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Iceland.png"), phone_code: "+354", name: "Iceland", alpha2_code: "IS", alpha3_code: "ISL", numeric_code: "352"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of India.png"), phone_code: "+91", name: "India", alpha2_code: "IN", alpha3_code: "IND", numeric_code: "356"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Indonesia.png"), phone_code: "+62", name: "Indonesia", alpha2_code: "ID", alpha3_code: "IDN", numeric_code: "360"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Iran.png"), phone_code: "+98", name: "Iran, Islamic Republic of", alpha2_code: "IR", alpha3_code: "IRN", numeric_code: "364"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Iraq.png"), phone_code: "+964", name: "Iraq", alpha2_code: "IQ", alpha3_code: "IRQ", numeric_code: "368"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Ireland.png"), phone_code: "+353", name: "Ireland", alpha2_code: "IE", alpha3_code: "IRL", numeric_code: "372"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Isle of Man.png"), phone_code: "+", name: "Isle of Man ", alpha2_code: "IM", alpha3_code: "IMN", numeric_code: "833"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Israel.png"), phone_code: "+972", name: "Israel", alpha2_code: "IL", alpha3_code: "ISR", numeric_code: "376"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Italy.png"), phone_code: "+39", name: "Italy", alpha2_code: "IT", alpha3_code: "ITA", numeric_code: "380"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Jamaica.png"), phone_code: "+876", name: "Jamaica", alpha2_code: "JM", alpha3_code: "JAM", numeric_code: "388"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Japan.png"), phone_code: "+81", name: "Japan", alpha2_code: "JP", alpha3_code: "JPN", numeric_code: "392"},
      {   flag: nil, phone_code: "+", name: "Jersey", alpha2_code: "JE", alpha3_code: "JEY", numeric_code: "832"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Jordan.png"), phone_code: "+962", name: "Jordan", alpha2_code: "JO", alpha3_code: "JOR", numeric_code: "400"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Kazakhstan.png"), phone_code: "+7", name: "Kazakhstan", alpha2_code: "KZ", alpha3_code: "KAZ", numeric_code: "398"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Kenya.png"), phone_code: "+254", name: "Kenya", alpha2_code: "KE", alpha3_code: "KEN", numeric_code: "404"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Kiribati.png"), phone_code: "+686", name: "Kiribati", alpha2_code: "KI", alpha3_code: "KIR", numeric_code: "296"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of North Korea.png"), phone_code: "+850", name: "Korea (North)", alpha2_code: "KP", alpha3_code: "PRK", numeric_code: "408"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of South Korea.png"), phone_code: "+82", name: "Korea (South)", alpha2_code: "KR", alpha3_code: "KOR", numeric_code: "410"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Kuwait.png"), phone_code: "+965", name: "Kuwait", alpha2_code: "KW", alpha3_code: "KWT", numeric_code: "414"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Kyrgyzstan.png"), phone_code: "+996", name: "Kyrgyzstan", alpha2_code: "KG", alpha3_code: "KGZ", numeric_code: "417"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Laos.png"), phone_code: "+856", name: "Lao PDR", alpha2_code: "LA", alpha3_code: "LAO", numeric_code: "418"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Latvia.png"), phone_code: "+371", name: "Latvia", alpha2_code: "LV", alpha3_code: "LVA", numeric_code: "428"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Lebanon.png"), phone_code: "+961", name: "Lebanon", alpha2_code: "LB", alpha3_code: "LBN", numeric_code: "422"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Lesotho.png"), phone_code: "+266", name: "Lesotho", alpha2_code: "LS", alpha3_code: "LSO", numeric_code: "426"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Liberia.png"), phone_code: "+231", name: "Liberia", alpha2_code: "LR", alpha3_code: "LBR", numeric_code: "430"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Libya.png"), phone_code: "+218", name: "Libya", alpha2_code: "LY", alpha3_code: "LBY", numeric_code: "434"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Liechtenstein.png"), phone_code: "+423", name: "Liechtenstein", alpha2_code: "LI", alpha3_code: "LIE", numeric_code: "438"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Lithuania.png"), phone_code: "+370", name: "Lithuania", alpha2_code: "LT", alpha3_code: "LTU", numeric_code: "440"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Luxembourg.png"), phone_code: "+352", name: "Luxembourg", alpha2_code: "LU", alpha3_code: "LUX", numeric_code: "442"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Macedonia.png"), phone_code: "+389", name: "Macedonia, Republic of", alpha2_code: "MK", alpha3_code: "MKD", numeric_code: "807"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Madagascar.png"), phone_code: "+261", name: "Madagascar", alpha2_code: "MG", alpha3_code: "MDG", numeric_code: "450"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Malawi.png"), phone_code: "+265", name: "Malawi", alpha2_code: "MW", alpha3_code: "MWI", numeric_code: "454"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Malaysia.png"), phone_code: "+60", name: "Malaysia", alpha2_code: "MY", alpha3_code: "MYS", numeric_code: "458"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Maldives.png"), phone_code: "+960", name: "Maldives", alpha2_code: "MV", alpha3_code: "MDV", numeric_code: "462"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mali.png"), phone_code: "+223", name: "Mali", alpha2_code: "ML", alpha3_code: "MLI", numeric_code: "466"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Malta.png"), phone_code: "+356", name: "Malta", alpha2_code: "MT", alpha3_code: "MLT", numeric_code: "470"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Marshall Islands.png"), phone_code: "+692", name: "Marshall Islands", alpha2_code: "MH", alpha3_code: "MHL", numeric_code: "584"},
      {   flag: nil, phone_code: "+", name: "Martinique", alpha2_code: "MQ", alpha3_code: "MTQ", numeric_code: "474"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mauritania.png"), phone_code: "+222", name: "Mauritania", alpha2_code: "MR", alpha3_code: "MRT", numeric_code: "478"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mauritius.png"), phone_code: "+230", name: "Mauritius", alpha2_code: "MU", alpha3_code: "MUS", numeric_code: "480"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mayotte.png"), phone_code: "+262", name: "Mayotte", alpha2_code: "YT", alpha3_code: "MYT", numeric_code: "175"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mexico.png"), phone_code: "+52", name: "Mexico", alpha2_code: "MX", alpha3_code: "MEX", numeric_code: "484"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Micronesia.png"), phone_code: "+691", name: "Micronesia, Federated States of", alpha2_code: "FM", alpha3_code: "FSM", numeric_code: "583"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Moldavia.png"), phone_code: "+373", name: "Moldova", alpha2_code: "MD", alpha3_code: "MDA", numeric_code: "498"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Monaco.png"), phone_code: "+377", name: "Monaco", alpha2_code: "MC", alpha3_code: "MCO", numeric_code: "492"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mongolia.png"), phone_code: "+976", name: "Mongolia", alpha2_code: "MN", alpha3_code: "MNG", numeric_code: "496"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Montenegro.png"), phone_code: "+382", name: "Montenegro", alpha2_code: "ME", alpha3_code: "MNE", numeric_code: "499"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Montserrat.png"), phone_code: "+664", name: "Montserrat", alpha2_code: "MS", alpha3_code: "MSR", numeric_code: "500"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Morocco.png"), phone_code: "+212", name: "Morocco", alpha2_code: "MA", alpha3_code: "MAR", numeric_code: "504"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Mozambique.png"), phone_code: "+258", name: "Mozambique", alpha2_code: "MZ", alpha3_code: "MOZ", numeric_code: "508"},
      {   flag: nil, phone_code: "+95", name: "Myanmar", alpha2_code: "MM", alpha3_code: "MMR", numeric_code: "104"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Namibia.png"), phone_code: "+264", name: "Namibia", alpha2_code: "NA", alpha3_code: "NAM", numeric_code: "516"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Nauru.png"), phone_code: "+674", name: "Nauru", alpha2_code: "NR", alpha3_code: "NRU", numeric_code: "520"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Nepal.png"), phone_code: "+977", name: "Nepal", alpha2_code: "NP", alpha3_code: "NPL", numeric_code: "524"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Netherlands.png"), phone_code: "+31", name: "Netherlands", alpha2_code: "NL", alpha3_code: "NLD", numeric_code: "528"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Netherlands Antilles.png"), phone_code: "+599", name: "Netherlands Antilles", alpha2_code: "AN", alpha3_code: "ANT", numeric_code: "530"},
      {   flag: nil, phone_code: "+687", name: "New Caledonia", alpha2_code: "NC", alpha3_code: "NCL", numeric_code: "540"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of New Zealand.png"), phone_code: "+64", name: "New Zealand", alpha2_code: "NZ", alpha3_code: "NZL", numeric_code: "554"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Nicaragua.png"), phone_code: "+505", name: "Nicaragua", alpha2_code: "NI", alpha3_code: "NIC", numeric_code: "558"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Niger.png"), phone_code: "+227", name: "Niger", alpha2_code: "NE", alpha3_code: "NER", numeric_code: "562"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Nigeria.png"), phone_code: "+234", name: "Nigeria", alpha2_code: "NG", alpha3_code: "NGA", numeric_code: "566"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Niue.png"), phone_code: "+683", name: "Niue", alpha2_code: "NU", alpha3_code: "NIU", numeric_code: "570"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Norfolk Island.png"), phone_code: "+", name: "Norfolk Island", alpha2_code: "NF", alpha3_code: "NFK", numeric_code: "574"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Northern Mariana Islands.png"), phone_code: "+", name: "Northern Mariana Islands", alpha2_code: "MP", alpha3_code: "MNP", numeric_code: "580"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Norway.png"), phone_code: "+47", name: "Norway", alpha2_code: "NO", alpha3_code: "NOR", numeric_code: "578"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Oman.png"), phone_code: "+968", name: "Oman", alpha2_code: "OM", alpha3_code: "OMN", numeric_code: "512"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Pakistan.png"), phone_code: "+92", name: "Pakistan", alpha2_code: "PK", alpha3_code: "PAK", numeric_code: "586"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Palau.png"), phone_code: "+680", name: "Palau", alpha2_code: "PW", alpha3_code: "PLW", numeric_code: "585"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Palestine.png"), phone_code: "+970", name: "Palestinian Territory", alpha2_code: "PS", alpha3_code: "PSE", numeric_code: "275"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Panama.png"), phone_code: "+507", name: "Panama", alpha2_code: "PA", alpha3_code: "PAN", numeric_code: "591"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Papua New Guinea.png"), phone_code: "+675", name: "Papua New Guinea", alpha2_code: "PG", alpha3_code: "PNG", numeric_code: "598"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Paraguay.png"), phone_code: "+595", name: "Paraguay", alpha2_code: "PY", alpha3_code: "PRY", numeric_code: "600"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Peru.png"), phone_code: "+51", name: "Peru", alpha2_code: "PE", alpha3_code: "PER", numeric_code: "604"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Philippines.png"), phone_code: "+63", name: "Philippines", alpha2_code: "PH", alpha3_code: "PHL", numeric_code: "608"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Pitcairn Islands.png"), phone_code: "+", name: "Pitcairn", alpha2_code: "PN", alpha3_code: "PCN", numeric_code: "612"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Poland.png"), phone_code: "+48", name: "Poland", alpha2_code: "PL", alpha3_code: "POL", numeric_code: "616"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Portugal.png"), phone_code: "+351", name: "Portugal", alpha2_code: "PT", alpha3_code: "PRT", numeric_code: "620"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Puerto Rico.png"), phone_code: "+", name: "Puerto Rico", alpha2_code: "PR", alpha3_code: "PRI", numeric_code: "630"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Qatar.png"), phone_code: "+974", name: "Qatar", alpha2_code: "QA", alpha3_code: "QAT", numeric_code: "634"},
      {   flag: nil, phone_code: "+262", name: "Reunion Island", alpha2_code: "RE", alpha3_code: "REU", numeric_code: "638"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Romania.png"), phone_code: "+40", name: "Romania", alpha2_code: "RO", alpha3_code: "ROU", numeric_code: "642"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Russia.png"), phone_code: "+7", name: "Russian Federation", alpha2_code: "RU", alpha3_code: "RUS", numeric_code: "643"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Rwanda.png"), phone_code: "+250", name: "Rwanda", alpha2_code: "RW", alpha3_code: "RWA", numeric_code: "646"},
      {   flag: nil, phone_code: "+", name: "Saint-Barth&eacute;lemy", alpha2_code: "BL", alpha3_code: "BLM", numeric_code: "652"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saint Helena.png"), phone_code: "+290", name: "Saint Helena", alpha2_code: "SH", alpha3_code: "SHN", numeric_code: "654"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saint Kitts and Nevis.png"), phone_code: "+869", name: "Saint Kitts and Nevis", alpha2_code: "KN", alpha3_code: "KNA", numeric_code: "659"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saint Lucia.png"), phone_code: "+758", name: "Saint Lucia", alpha2_code: "LC", alpha3_code: "LCA", numeric_code: "662"},
      {   flag: nil, phone_code: "+721", name: "Saint-Martin (French part)", alpha2_code: "MF", alpha3_code: "MAF", numeric_code: "663"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saint Pierre and Miquelon.png"), phone_code: "+508", name: "Saint Pierre and Miquelon ", alpha2_code: "PM", alpha3_code: "SPM", numeric_code: "666"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saint Vincent.png"), phone_code: "+784", name: "Saint Vincent and Grenadines", alpha2_code: "VC", alpha3_code: "VCT", numeric_code: "670"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Samoa.png"), phone_code: "+", name: "Samoa", alpha2_code: "WS", alpha3_code: "WSM", numeric_code: "882"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of San Marino.png"), phone_code: "+378", name: "San Marino", alpha2_code: "SM", alpha3_code: "SMR", numeric_code: "674"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sao Tome and Principe.png"), phone_code: "+239", name: "Sao Tome and Principe", alpha2_code: "ST", alpha3_code: "STP", numeric_code: "678"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Saudi Arabia.png"), phone_code: "+966", name: "Saudi Arabia", alpha2_code: "SA", alpha3_code: "SAU", numeric_code: "682"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Senegal.png"), phone_code: "+221", name: "Senegal", alpha2_code: "SN", alpha3_code: "SEN", numeric_code: "686"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Serbia.png"), phone_code: "+381", name: "Serbia", alpha2_code: "RS", alpha3_code: "SRB", numeric_code: "688"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Seychelles.png"), phone_code: "+248", name: "Seychelles", alpha2_code: "SC", alpha3_code: "SYC", numeric_code: "690"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sierra Leone.png"), phone_code: "+232", name: "Sierra Leone", alpha2_code: "SL", alpha3_code: "SLE", numeric_code: "694"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Singapore.png"), phone_code: "+65", name: "Singapore", alpha2_code: "SG", alpha3_code: "SGP", numeric_code: "702"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Slovakia.png"), phone_code: "+421", name: "Slovakia", alpha2_code: "SK", alpha3_code: "SVK", numeric_code: "703"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Slovenia.png"), phone_code: "+386", name: "Slovenia", alpha2_code: "SI", alpha3_code: "SVN", numeric_code: "705"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Solomon Islands.png"), phone_code: "+677", name: "Solomon Islands", alpha2_code: "SB", alpha3_code: "SLB", numeric_code: "090"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Somalia.png"), phone_code: "+252", name: "Somalia", alpha2_code: "SO", alpha3_code: "SOM", numeric_code: "706"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of South Africa.png"), phone_code: "+27", name: "South Africa", alpha2_code: "ZA", alpha3_code: "ZAF", numeric_code: "710"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of South Georgia and the South Sandwich Islands.png"), phone_code: "+", name: "South Georgia and the South Sandwich Islands", alpha2_code: "GS", alpha3_code: "SGS", numeric_code: "239"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sudan.png"), phone_code: "+2011", name: "South Sudan", alpha2_code: "SS", alpha3_code: "SSD", numeric_code: "728"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Spain.png"), phone_code: "+34", name: "Spain", alpha2_code: "ES", alpha3_code: "ESP", numeric_code: "724"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sri Lanka.png"), phone_code: "+94", name: "Sri Lanka", alpha2_code: "LK", alpha3_code: "LKA", numeric_code: "144"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sudan.png"), phone_code: "+249", name: "Sudan", alpha2_code: "SD", alpha3_code: "SDN", numeric_code: "736"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Suriname.png"), phone_code: "+597", name: "Suriname", alpha2_code: "SR", alpha3_code: "SUR", numeric_code: "740"},
      {   flag: nil, phone_code: "+", name: "Svalbard and Jan Mayen Islands ", alpha2_code: "SJ", alpha3_code: "SJM", numeric_code: "744"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Swaziland.png"), phone_code: "+268", name: "Swaziland", alpha2_code: "SZ", alpha3_code: "SWZ", numeric_code: "748"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Sweden.png"), phone_code: "+46", name: "Sweden", alpha2_code: "SE", alpha3_code: "SWE", numeric_code: "752"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Switzerland.png"), phone_code: "+41", name: "Switzerland", alpha2_code: "CH", alpha3_code: "CHE", numeric_code: "756"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Syria.png"), phone_code: "+963", name: "Syrian Arab Republic</a> (Syria)", alpha2_code: "SY", alpha3_code: "SYR", numeric_code: "760"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Taiwan.png"), phone_code: "+886", name: "Taiwan, Republic of China ", alpha2_code: "TW", alpha3_code: "TWN", numeric_code: "158"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Tajikistan.png"), phone_code: "+992", name: "Tajikistan", alpha2_code: "TJ", alpha3_code: "TJK", numeric_code: "762"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Tanzania.png"), phone_code: "+255", name: "Tanzania</a>, United Republic of ", alpha2_code: "TZ", alpha3_code: "TZA", numeric_code: "834"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Thailand.png"), phone_code: "+66", name: "Thailand", alpha2_code: "TH", alpha3_code: "THA", numeric_code: "764"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Timor Leste.png"), phone_code: "+", name: "Timor-Leste", alpha2_code: "TL", alpha3_code: "TLS", numeric_code: "626"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Togo.png"), phone_code: "+228", name: "Togo", alpha2_code: "TG", alpha3_code: "TGO", numeric_code: "768"},
      {   flag: nil, phone_code: "+690", name: "Tokelau ", alpha2_code: "TK", alpha3_code: "TKL", numeric_code: "772"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Tonga.png"), phone_code: "+676", name: "Tonga", alpha2_code: "TO", alpha3_code: "TON", numeric_code: "776"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Trinidad and Tobago.png"), phone_code: "+868", name: "Trinidad and Tobago", alpha2_code: "TT", alpha3_code: "TTO", numeric_code: "780"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Tunisia.png"), phone_code: "+216", name: "Tunisia", alpha2_code: "TN", alpha3_code: "TUN", numeric_code: "788"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Turkey.png"), phone_code: "+90", name: "Turkey", alpha2_code: "TR", alpha3_code: "TUR", numeric_code: "792"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Turkmenistan.png"), phone_code: "+993", name: "Turkmenistan", alpha2_code: "TM", alpha3_code: "TKM", numeric_code: "795"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Turks and Caicos Islands.png"), phone_code: "+649", name: "Turks and Caicos Islands ", alpha2_code: "TC", alpha3_code: "TCA", numeric_code: "796"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Tuvalu.png"), phone_code: "+688", name: "Tuvalu", alpha2_code: "TV", alpha3_code: "TUV", numeric_code: "798"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Uganda.png"), phone_code: "+256", name: "Uganda", alpha2_code: "UG", alpha3_code: "UGA", numeric_code: "800"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Ukraine.png"), phone_code: "+380", name: "Ukraine", alpha2_code: "UA", alpha3_code: "UKR", numeric_code: "804"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of United Arab Emirates.png"), phone_code: "+971", name: "United Arab Emirates", alpha2_code: "AE", alpha3_code: "ARE", numeric_code: "784"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of United Kingdom.png"), phone_code: "+44", name: "United Kingdom", alpha2_code: "GB", alpha3_code: "GBR", numeric_code: "826"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of United States.png"), phone_code: "+1", name: "United States of America", alpha2_code: "US", alpha3_code: "USA", numeric_code: "840"},
      {   flag: nil, phone_code: "+", name: "US Minor Outlying Islands", alpha2_code: "UM", alpha3_code: "UMI", numeric_code: "581"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Uruguay.png"), phone_code: "+598", name: "Uruguay", alpha2_code: "UY", alpha3_code: "URY", numeric_code: "858"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Uzbekistan.png"), phone_code: "+998", name: "Uzbekistan", alpha2_code: "UZ", alpha3_code: "UZB", numeric_code: "860"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Vanuatu.png"), phone_code: "+678", name: "Vanuatu", alpha2_code: "VU", alpha3_code: "VUT", numeric_code: "548"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Venezuela.png"), phone_code: "+58", name: "Venezuela (Bolivarian Republic)", alpha2_code: "VE", alpha3_code: "VEN", numeric_code: "862"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Vietnam.png"), phone_code: "+84", name: "Viet Nam", alpha2_code: "VN", alpha3_code: "VNM", numeric_code: "704"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Virgin Islands.png"), phone_code: "+", name: "Virgin Islands, US", alpha2_code: "VI", alpha3_code: "VIR", numeric_code: "850"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Wallis and Futuna.png"), phone_code: "+681", name: "Wallis and Futuna Islands", alpha2_code: "WF", alpha3_code: "WLF", numeric_code: "876"},
      {   flag: nil, phone_code: "+", name: "Western Sahara", alpha2_code: "EH", alpha3_code: "ESH", numeric_code: "732"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Yemen.png"), phone_code: "+967", name: "Yemen", alpha2_code: "YE", alpha3_code: "YEM", numeric_code: "887"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Zambia.png"), phone_code: "+260", name: "Zambia", alpha2_code: "ZM", alpha3_code: "ZMB", numeric_code: "894"},
      {   flag: File.open("#{ Rails.root }/public/images/country_select/Flag of Zimbabwe.png"), phone_code: "+263", name: "Zimbabwe", alpha2_code: "ZW", alpha3_code: "ZWE", numeric_code: "716"}
  ]

  countries_attributes.each do |attributes|
    c = Country.create attributes
    puts c.name, c.errors.full_messages unless c.valid?
    print '.'
  end
end
